print("точка A [x y]")
Ax = int(input())
Ay = int(input())
print(Ax,Ay)
print("Точка B [x y]")
Bx = int(input())
By = int(input())
print(Bx,By)
print('Точка C [x y]')
Cx = int(input())
Cy = int(input())
print(Cx,Cy)
